apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    component: "alertmanager"
    app: prometheus
    release: release-name
    chart: prometheus-15.16.1
    heritage: Helm
  name: release-name-prometheus-alertmanager
  namespace: default